import type { LucideIcon } from "lucide-react";
import {
  Hammer,
  Bell,
  ArrowLeft,
  Construction,
  Search,
  Link,
  Globe,
  Tag,
  FileText,
  Image,
  Youtube,
  Code,
  Database,
  DollarSign,
  Percent,
  Calendar,
  Instagram,
  Twitter,
  Facebook,
  PenTool,
  Palette,
  Type,
  Edit,
  BarChart2,
  Grid,
  Lock,
  User,
  Settings,
  Download,
  Upload,
  Share2,
  Copy,
  Printer,
  Layers,
  PieChart,
  CreditCard,
  Clock,
  Award,
  TrendingUp,
  Zap,
  Heart,
  Star,
  CheckCircle2,
  AlertCircle,
  HelpCircle,
  Menu,
  X,
  Plus,
  Minus,
  Filter,
  RotateCw,
  RefreshCw,
  ExternalLink
} from "lucide-react";

export const Icons = {
  // Basic UI
  tool: Hammer,
  bell: Bell,
  arrowLeft: ArrowLeft,
  construction: Construction,
  menu: Menu,
  close: X,
  plus: Plus,
  minus: Minus,
  externalLink: ExternalLink,
  check: CheckCircle2,
  error: AlertCircle,
  help: HelpCircle,
  
  // Category Icons
  search: Search,
  link: Link,
  globe: Globe,
  tag: Tag,
  fileText: FileText,
  image: Image,
  youtube: Youtube,
  code: Code,
  database: Database,
  dollar: DollarSign,
  percent: Percent,
  calendar: Calendar,
  instagram: Instagram,
  twitter: Twitter,
  facebook: Facebook,
  penTool: PenTool,
  palette: Palette,
  type: Type,
  edit: Edit,
  
  // Tool Functionality
  download: Download,
  upload: Upload,
  share: Share2,
  copy: Copy,
  print: Printer,
  layers: Layers,
  chart: BarChart2,
  pieChart: PieChart,
  creditCard: CreditCard,
  clock: Clock,
  award: Award,
  trending: TrendingUp,
  zap: Zap,
  heart: Heart,
  star: Star,
  
  // Actions
  filter: Filter,
  refresh: RefreshCw,
  rotate: RotateCw,
  settings: Settings,
  user: User
} as const;

export type IconName = keyof typeof Icons;